spring.application.name=CRUD-intern

spring.datasource.url=jdbc:postgresql://localhost:5432/CRUD-intern
spring.datasource.driver-class-name= org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=0000

